/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const WaitlistEntry = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'isWhatsApp' : IDL.Bool,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const ReviewStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'city' : IDL.Text,
  'rating' : IDL.Nat,
  'message' : IDL.Text,
  'createdAt' : IDL.Int,
  'status' : ReviewStatus,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getEntries' : IDL.Func([], [IDL.Vec(WaitlistEntry)], ['query']),
  'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitWaitlist' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getLeadStatuses' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))], ['query']),
  'updateLeadStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updatePost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getPendingReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'approveReview' : IDL.Func([IDL.Nat], [], []),
  'deleteReview' : IDL.Func([IDL.Nat], [], []),
  'addManualReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const WaitlistEntry = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'isWhatsApp' : IDL.Bool,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const ReviewStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'city' : IDL.Text,
    'rating' : IDL.Nat,
    'message' : IDL.Text,
    'createdAt' : IDL.Int,
    'status' : ReviewStatus,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getEntries' : IDL.Func([], [IDL.Vec(WaitlistEntry)], ['query']),
    'getPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitWaitlist' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getLeadStatuses' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))], ['query']),
    'updateLeadStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updatePost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getPendingReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'approveReview' : IDL.Func([IDL.Nat], [], []),
    'deleteReview' : IDL.Func([IDL.Nat], [], []),
    'addManualReview' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };
